// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ajex

import (
	"context"
	"github.com/omniful/shipping-service/internal/domain/interfaces"
)

// Injectors from wire.go:

func AjexService(ctx context.Context, psmRepo interfaces.PartnerShippingMethodRepository, spRepo interfaces.ShippingPartnerRepository, cmRepo interfaces.CityMappingRepository, tcmRepo interfaces.TenantCityMappingRepository, orderRepo interfaces.OrderRepository, opRepo interfaces.OrderPartnerRepository) (*Service, error) {
	requestAdapter := ProvideRequestAdapter(spRepo, cmRepo, tcmRepo)
	responseAdapter := ProvideResponseAdapter(opRepo, orderRepo)
	service := NewService(ctx, psmRepo, requestAdapter, responseAdapter)
	return service, nil
}
